import Header from "@/components/layouts/Header";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className="w-full max-w-[1280px] h-full min-h-[calc(100vh-72px)] m-auto pt-12 px-4">
          {children}
        </main>
      </body>
    </html>
  );
}
